const ActionsTypes = {
  FETCH_PRODUCT: "FETCH_PRODUCT",
  SET_PRODUCT: "SET_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
export default ActionsTypes;
